export const THEMES = {
  'bento-dark': {
    name: 'Gen-Z Bento (Dark)',
    bgWrapper: 'min-h-screen bg-zinc-950 text-white font-sans pb-20 selection:bg-purple-500/30',
    renderBlobs: true,
    card: 'bg-zinc-900 border border-zinc-800 rounded-[2rem] p-6 md:p-8 shadow-2xl relative overflow-hidden group',
    cardHover: 'hover:border-purple-500/50 transition duration-500',
    title: 'text-4xl md:text-5xl font-black tracking-tight mb-2',
    accentText: 'text-purple-400',
    taglineBadge: 'px-4 py-2 bg-gradient-to-r from-purple-500/20 to-pink-500/20 border border-purple-500/30 rounded-2xl text-purple-200 text-sm font-semibold inline-block shadow-lg',
    primaryButton: 'bg-white hover:bg-zinc-200 text-black font-extrabold rounded-xl shadow-xl',
    skillBadge: 'px-4 py-2 bg-zinc-800/80 hover:bg-zinc-700 border border-zinc-700/50 rounded-xl text-sm font-semibold transition',
    socialIconBg: 'bg-zinc-800/50 hover:bg-zinc-700/80 rounded-2xl',
    projectCard: 'bg-zinc-900 border border-zinc-800 hover:border-purple-500/50 rounded-2xl p-5 group transition',
    projectThumb: 'bg-zinc-950/50 border border-zinc-800/50 grayscale group-hover:grayscale-0 rounded-xl mb-5 transition duration-500',
  },
  'brutalism': {
    name: 'Neo Brutalism',
    bgWrapper: 'min-h-screen bg-[#FFF000] text-black font-sans pb-20 selection:bg-black selection:text-white',
    renderBlobs: false,
    card: 'bg-white border-4 border-black rounded-none p-6 md:p-8 shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] relative transition-all group',
    cardHover: 'hover:-translate-y-1 hover:shadow-[12px_12px_0px_0px_rgba(0,0,0,1)]',
    title: 'text-4xl md:text-5xl font-black uppercase tracking-tight mb-2',
    accentText: 'text-blue-700 font-bold',
    taglineBadge: 'px-4 py-2 bg-[#FF90E8] border-2 border-black font-black text-black rounded-none uppercase text-xs inline-block',
    primaryButton: 'bg-black hover:bg-zinc-800 text-white font-black rounded-none border-2 border-transparent hover:border-black uppercase',
    skillBadge: 'px-4 py-2 bg-white border-2 border-black font-black uppercase text-sm',
    socialIconBg: 'bg-white border-2 border-black hover:bg-[#FF90E8] rounded-none group',
    projectCard: 'bg-white border-4 border-black p-5 rounded-none shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] group hover:-translate-y-1 hover:shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] transition-all',
    projectThumb: 'bg-zinc-100 border-2 border-black rounded-none mb-5',
  },
  'minimal-light': {
    name: 'Minimal Light',
    bgWrapper: 'min-h-screen bg-[#FAFAFA] text-zinc-900 font-sans pb-20',
    renderBlobs: false,
    card: 'bg-white border border-zinc-100 hover:shadow-xl hover:border-zinc-200 rounded-3xl p-6 md:p-8 transition duration-300 group',
    cardHover: '',
    title: 'text-3xl md:text-4xl font-normal tracking-tight mb-2 text-zinc-800',
    accentText: 'text-zinc-500 font-medium',
    taglineBadge: 'px-3 py-1 bg-zinc-100 text-zinc-600 rounded-md font-medium text-xs inline-block',
    primaryButton: 'bg-zinc-900 hover:bg-black text-white font-medium rounded-full shadow-md',
    skillBadge: 'px-4 py-2 bg-zinc-50 text-zinc-600 border border-zinc-100 rounded-full text-sm font-medium',
    socialIconBg: 'bg-transparent border border-zinc-200 hover:bg-zinc-50 rounded-full text-zinc-900',
    projectCard: 'bg-white border border-zinc-100 hover:border-zinc-300 rounded-2xl p-5 group transition duration-300',
    projectThumb: 'bg-zinc-50 rounded-xl mb-5 overflow-hidden',
  },
  'cyberpunk': {
    name: 'Night City Cyberpunk',
    bgWrapper: 'min-h-screen bg-[#0a0a0c] text-[#00ff41] font-mono pb-20 selection:bg-[#ff003c] selection:text-white',
    renderBlobs: false,
    card: 'bg-[#111] border border-[#00ff41]/30 rounded-none p-6 md:p-8 shadow-[0_0_15px_rgba(0,255,65,0.1)] relative group before:absolute before:top-0 before:left-0 before:w-full before:h-1 before:bg-gradient-to-r before:from-[#ff003c] before:to-[#00ff41]',
    cardHover: 'hover:border-[#00ff41]/80 hover:shadow-[0_0_30px_rgba(0,255,65,0.2)] transition-all duration-300',
    title: 'text-4xl md:text-5xl font-bold tracking-tighter mb-2 text-[#ff003c] uppercase',
    accentText: 'text-[#0df]',
    taglineBadge: 'px-4 py-2 bg-[#ff003c]/10 border border-[#ff003c]/50 text-[#ff003c] text-xs font-bold uppercase tracking-widest inline-block',
    primaryButton: 'bg-[#00ff41] hover:bg-[#00ff41]/80 text-[#0a0a0c] font-bold rounded-none uppercase tracking-widest',
    skillBadge: 'px-4 py-2 bg-[#111] text-[#0df] border border-[#0df]/30 rounded-none text-xs uppercase',
    socialIconBg: 'bg-[#111] border border-[#00ff41]/30 hover:bg-[#00ff41] hover:text-[#0a0a0c] rounded-none',
    projectCard: 'bg-[#111] border border-[#00ff41]/30 hover:border-[#ff003c] p-5 rounded-none group transition-all duration-300 block',
    projectThumb: 'bg-black border border-[#00ff41]/30 opacity-70 group-hover:opacity-100 mb-5 relative',
  },
  'terminal': {
    name: 'Hacker Terminal',
    bgWrapper: 'min-h-screen bg-black text-[#33ff00] font-mono pb-20 selection:bg-[#33ff00] selection:text-black',
    renderBlobs: false,
    card: 'bg-black border border-[#33ff00] rounded-none p-6 md:p-8',
    cardHover: '',
    title: 'text-2xl md:text-3xl font-bold mb-2 before:content-[">_"] before:mr-2',
    accentText: 'text-[#33ff00]/70',
    taglineBadge: 'px-2 py-1 bg-transparent border border-dashed border-[#33ff00]/50 text-[#33ff00] text-xs inline-block',
    primaryButton: 'bg-transparent hover:bg-[#33ff00] border border-[#33ff00] hover:text-black text-[#33ff00] font-bold rounded-none uppercase',
    skillBadge: 'px-3 py-1 bg-transparent border border-[#33ff00]/50 text-[#33ff00] rounded-none text-xs',
    socialIconBg: 'bg-transparent border border-[#33ff00] hover:bg-[#33ff00] hover:text-black rounded-none',
    projectCard: 'bg-black border border-[#33ff00]/50 hover:border-[#33ff00] p-5 rounded-none',
    projectThumb: 'bg-[#33ff00]/10 mb-5 border border-[#33ff00]/30',
  },
  'retro-sunset': {
    name: 'Retro Sunset',
    bgWrapper: 'min-h-screen bg-gradient-to-b from-[#2b1055] via-[#7597de] to-[#ff9e7d] text-orange-50 font-sans pb-20',
    renderBlobs: false,
    card: 'bg-[#2b1055]/60 backdrop-blur-md border border-pink-500/30 rounded-3xl p-6 md:p-8 shadow-[0_0_40px_rgba(255,107,157,0.2)] group',
    cardHover: 'hover:border-pink-500/60 transition duration-500',
    title: 'text-4xl md:text-5xl font-black italic tracking-wide mb-2 text-transparent bg-clip-text bg-gradient-to-b from-yellow-300 to-pink-500 drop-shadow-[0_2px_2px_rgba(255,0,128,0.8)]',
    accentText: 'text-cyan-300',
    taglineBadge: 'px-4 py-2 bg-gradient-to-r from-pink-500/40 to-orange-500/40 border border-pink-500/50 rounded-full text-yellow-200 text-sm font-semibold inline-block',
    primaryButton: 'bg-gradient-to-r from-cyan-400 to-blue-500 hover:from-cyan-300 hover:to-blue-400 text-black font-extrabold rounded-full shadow-[0_0_15px_rgba(0,255,255,0.5)]',
    skillBadge: 'px-4 py-2 bg-pink-900/40 border border-pink-500/30 rounded-full text-pink-200 text-sm font-bold',
    socialIconBg: 'bg-indigo-900/50 border border-indigo-500/50 hover:bg-pink-500 rounded-full',
    projectCard: 'bg-[#2b1055]/50 border border-indigo-500/30 hover:border-pink-500/50 rounded-2xl p-5 group transition duration-300',
    projectThumb: 'bg-indigo-900/50 rounded-xl mb-5 border border-indigo-500/30 rounded-xl',
  },
  'corporate': {
    name: 'Executive Corporate',
    bgWrapper: 'min-h-screen bg-[#F8F9FA] text-[#212529] font-serif pb-20',
    renderBlobs: false,
    card: 'bg-white border-t-8 border-[#003366] rounded-sm p-6 md:p-10 shadow-lg group',
    cardHover: '',
    title: 'text-4xl md:text-5xl font-bold tracking-tight mb-2 text-[#003366]',
    accentText: 'text-[#495057] font-sans uppercase text-sm tracking-widest',
    taglineBadge: 'px-0 py-1 border-b border-[#003366] text-[#003366] font-bold text-sm inline-block rounded-none font-sans',
    primaryButton: 'bg-[#003366] hover:bg-[#002244] text-white font-bold rounded-sm font-sans',
    skillBadge: 'px-4 py-2 bg-[#E9ECEF] text-[#495057] rounded-sm text-sm font-sans font-semibold border-l-4 border-[#003366]',
    socialIconBg: 'bg-transparent text-[#003366] hover:bg-[#E9ECEF] rounded-sm border border-[#DEE2E6]',
    projectCard: 'bg-white border border-[#DEE2E6] hover:shadow-md rounded-sm p-5 group transition',
    projectThumb: 'bg-[#E9ECEF] rounded-none mb-5',
  },
  'ocean-glass': {
    name: 'Ocean Glassmorphism',
    bgWrapper: 'min-h-screen bg-gradient-to-br from-[#0f2027] via-[#203a43] to-[#2c5364] text-white font-sans pb-20 selection:bg-cyan-500/30',
    renderBlobs: true,
    card: 'bg-white/5 backdrop-blur-xl border border-white/10 rounded-[2.5rem] p-6 md:p-8 shadow-[0_8px_32px_0_rgba(31,38,135,0.37)] group',
    cardHover: 'hover:bg-white/10 hover:border-white/20 transition duration-500',
    title: 'text-4xl md:text-5xl font-extrabold tracking-tight mb-2 text-transparent bg-clip-text bg-gradient-to-r from-cyan-200 to-blue-200',
    accentText: 'text-cyan-300',
    taglineBadge: 'px-4 py-2 bg-cyan-500/20 border border-cyan-500/30 rounded-2xl text-cyan-50 text-sm font-medium inline-block',
    primaryButton: 'bg-cyan-500 hover:bg-cyan-400 text-[#0f2027] font-bold rounded-2xl shadow-[0_0_15px_rgba(6,182,212,0.4)]',
    skillBadge: 'px-4 py-2 bg-white/5 border border-white/10 rounded-2xl text-cyan-100 text-sm hover:bg-white/10 transition',
    socialIconBg: 'bg-white/5 border border-white/10 hover:bg-cyan-500 rounded-2xl',
    projectCard: 'bg-white/5 backdrop-blur-md border border-white/10 hover:border-cyan-500/50 rounded-3xl p-5 group transition duration-300',
    projectThumb: 'bg-black/20 rounded-2xl mb-5 overflow-hidden',
  },
  'velvet': {
    name: 'Royal Velvet',
    bgWrapper: 'min-h-screen bg-[#1A0B13] text-[#F3E8EE] font-serif pb-20 selection:bg-[#800020] selection:text-white',
    renderBlobs: false,
    card: 'bg-[#2A111C] border border-[#4A1D31] rounded-lg p-6 md:p-10 shadow-2xl relative overflow-hidden group',
    cardHover: 'hover:border-[#800020] transition duration-500',
    title: 'text-4xl md:text-5xl font-normal tracking-wide mb-2 text-[#FFD700]',
    accentText: 'text-[#D4AF37]',
    taglineBadge: 'px-4 py-2 bg-[#4A1D31]/50 border border-[#800020] rounded-none text-[#FFD700] text-sm italic inline-block',
    primaryButton: 'bg-gradient-to-r from-[#D4AF37] to-[#AA7C11] hover:from-[#F9DF9F] hover:to-[#D4AF37] text-[#1A0B13] font-bold rounded-sm uppercase tracking-widest',
    skillBadge: 'px-4 py-2 bg-[#1A0B13] border border-[#D4AF37]/50 rounded-none text-[#D4AF37] text-sm',
    socialIconBg: 'bg-transparent border border-[#4A1D31] text-[#D4AF37] hover:bg-[#4A1D31] rounded-full',
    projectCard: 'bg-[#2A111C] border border-[#4A1D31] hover:border-[#D4AF37] rounded-none p-5 group transition',
    projectThumb: 'bg-[#1A0B13] mb-5 border border-[#4A1D31]/50',
  },
  'nova': {
    name: 'Nova Light (Tech)',
    bgWrapper: 'min-h-screen bg-[#f5f5f7] text-[#1d1d1f] font-sans pb-20',
    renderBlobs: true,
    card: 'bg-white/70 backdrop-blur-2xl border border-white rounded-[2rem] p-6 md:p-10 shadow-[0_10px_50px_rgba(0,0,0,0.05)] group',
    cardHover: 'border-white',
    title: 'text-4xl md:text-5xl font-bold tracking-tight mb-2 text-[#1d1d1f]',
    accentText: 'text-[#86868b] font-medium text-lg',
    taglineBadge: 'px-4 py-2 bg-[#f5f5f7] text-[#1d1d1f] rounded-full text-xs font-bold uppercase tracking-widest inline-block shadow-inner',
    primaryButton: 'bg-[#0071e3] hover:bg-[#0077ED] text-white font-medium rounded-full shadow-md',
    skillBadge: 'px-4 py-2 bg-white border border-[#e5e5ea] rounded-full text-[#1d1d1f] text-sm shadow-sm',
    socialIconBg: 'bg-white border border-[#e5e5ea] hover:bg-[#f5f5f7] shadow-sm rounded-full text-[#1d1d1f]',
    projectCard: 'bg-white border border-[#e5e5ea] hover:shadow-xl rounded-3xl p-5 group transition-all duration-300',
    projectThumb: 'bg-[#f5f5f7] rounded-2xl mb-5',
  }
};
